name: e2e tests on Windows

on:
  push:
    branches:
        win11-ci

jobs:

  e2e-tests:
    timeout-minutes: 90
    runs-on: [self-hosted, x64, win11]
    env:
      shell: pwsh
      SECRET: ${{ secrets.WIN11PRV_USERPASS }}
      HOME: C:/Users/tuctuc
    steps:
      - name: Remove Rancher Desktop distros from WSL
        continue-on-error: true
        run: PsExec64.exe -i -u chivo -p "$SECRET" -accepteula unregister-wsl.ps1

      - name: Cleanup Test Environment
        continue-on-error: true
        run: PsExec64.exe -i -u chivo -p "$SECRET" -accepteula clean-test-env.ps1
      - name: Install Scoop
        continue-on-error: true
        run: PsExec64.exe -i -u chivo -p "$SECRET" -accepteula install-scoop.ps1
      - name: Install Project Dependencies
        continue-on-error: true
        run: |
          PsExec64.exe -i -u chivo -p "$SECRET" -accepteula install-project-dependencies.ps1
      - name: Install node
        run: PsExec64.exe -i -u chivo -p "$SECRET" -accepteula install-node.ps1
      - name: Setup node
        run: PsExec64.exe -i -u chivo -p "$SECRET" -accepteula setup-node.ps1
      - name: Install node dependencies
        run: |
          PsExec64.exe -i -u chivo -p "$SECRET" -accepteula install-node-mod.ps1
      - name: Checkout repository
        run: |
          PsExec64.exe -i -u chivo -p "$SECRET" -accepteula checkout-repo.ps1
      - name: Run e2e Tests
        continue-on-error: false
        run: |
          PsExec64.exe -i -u chivo -p "$SECRET" -accepteula run-e2e-tests.ps1
